# Generated by Django 5.0.7 on 2024-08-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_rename_number_ordered_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(max_length=25, null=True, verbose_name='Client Name'),
        ),
    ]
